### ISSUE TITLE
'build-all' modifies system-level even when run without sudo

### ISSUE THREAD

**Issue by wstidolph** [ampf/AMPF#3] opened 2010-05-25 02:20 UTC
This surprised me, maybe we should think about some mechanism to get acknowledgement that "this will write in system directories" before running:

I ran 'ant build-all' and it dumped files into /usr/local/lib/gstreamer (and so forth); this surprised me, since I'm expecting that only to happen if I run under 'sudo' ... it worked because my account is in the 'wheel' group which lets me run commands using 'sudo ...' without a password, but I didn't expect 'ant build-all' to attempt to write there (or to run using sudo somehow).

The more normal behaviour would be 'configure; make; sudo make install' for a system install, or 'configure --prefix=... ; make ; make install' for a local non-system installation.

**Comment by gbowles** [comment] 2010-05-25 02:22
Ouch, that's definitely bad - again, are you using "ant build-all" ?  That's supposed to call build-components.sh with the --no-install option, which is supposed to skip the "make install" step.

**Comment by wstidolph** [comment] 2010-05-25 02:25
yep, just 'ant build-all'

**Comment by simontuffs** [comment] 2010-05-25 04:42
antl build-all (or ant build-components) should invokes the build-components.sh script with --no-install, like it used to invoke the build-all script.  Moreover, at this point we should cut out the extra install mechanism from that script, as I said in the other issue comment on this subject: that is legacy behavior and has no place in an RPM install driven process.  In all the time I've been doing MPF builds, the only time I've used build-all without --no-install is by accident, and that has messed up my system.  One of the reasons I wrapped it in ant with --no-install.  Kill it. +5.

**Comment by wstidolph** [comment] 2010-05-25 05:11
I'm not sure of what's going on with all this, but one comment: we should not tie our source buildability to a particular delivery packaging (RPM) - can I build this using autotools?

**Comment by simontuffs** [comment] 2010-05-28 05:45
This has been fixed: it was caused by not having quotes on the argument to the build-components.sh script when using --noinstall.  The fix has been multi-fold: make build-components not do --install by default, require --install to force an install, add --uninstall to let you clean up.  Same has been done for GRDF.

**Closed as completed by simontuffs** 2010-05-28 05:45 UTC
Labels: gbowles, simontuffs
